spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: your-github-client-id
            client-secret: your-github-client-secret
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

# logging:
#  level:
#    org.springframework.security: DEBUG
